//
//  QuizGenerator.swift
//  BaseaballQuiz
//
//  Created by applys on 7/8/25.
//

import Foundation
import SwiftData


// 퀴즈 유형 열거형
enum QuizType: CaseIterable {
    case imageQuiz // 이미지 퀴즈
    case oxQuiz    // OX 퀴즈
    case questionQuiz // 질문 퀴즈 (4지선다형)
}

// 퀴즈 데이터를 담을 구조체
struct Quiz: Identifiable {
    let id = UUID() // 각 퀴즈를 고유하게 식별하기 위한 ID
    let type: QuizType // 퀴즈 유형
    let question: String // 퀴즈 질문
    let imageUrl: URL? // 이미지 퀴즈일 경우 이미지 URL (옵션)
    let options: [String]? // 4지선다형 퀴즈일 경우 선택지 (옵션)
    let correctAnswer: String // 정답
    let explanation: String? // 정답에 대한 추가 설명 (옵션)
}


class QuizGenerator {
    private let allQuizzes: [Quiz] = [
        // 이미지 퀴즈
        Quiz(type: .imageQuiz,
             question: "이 선수는 누구일까요?",
             imageUrl: URL(string: "https://dimg.donga.com/wps/NEWS/IMAGE/2024/09/06/126884040.2.jpg")!,
             options: ["김광현", "류현진", "양의지", "이정후"],
             correctAnswer: "류현진",
             explanation: "한국 야구의 괴물 투수,  류현진 선수입니다."),
        Quiz(type: .imageQuiz,
             question: "다음은 어떤 구단의 로고일까요?",
             imageUrl: URL(string: "https://upload.wikimedia.org/wikipedia/ko/8/8a/LG_%ED%8A%B8%EC%9C%88%EC%8A%A4_%EB%A1%9C%EA%B3%A0.png")!,
             options: ["두산 베어스", "LG 트윈스", "SSG 랜더스", "NC 다이노스"],
             correctAnswer: "LG 트윈스",
             explanation: "서울을 연고로 하는  LG 트윈스 로고입니다."),
        Quiz(type: .imageQuiz,
             question: "이 야구장은 서울의 어느 구단이 함께 홈으로 사용하는 곳일까요?",
             imageUrl: URL(string: "https://img.sbs.co.kr/newimg/news/20230918/201834693.jpg")!,
             options: ["두산 & 키움", "LG & 키움", "두산 & LG", "SSG & KT"],
             correctAnswer: "두산 & LG",
             explanation: "서울을 연고로 하는 두 팀인  두산베어스와 LG트윈스입니다."),
        Quiz(type: .imageQuiz,
             question: "아래 이미지에서 시구를 하는 사람은 누구일까요?",
             imageUrl: URL(string: "https://spnimage.edaily.co.kr/images/photo/files/NP/S/2016/04/PS16041000071.jpg")!,
             options: ["김범수", "하하", "노홍철", "유재석"],
             correctAnswer: "하하",
             explanation: "이미지 속 시구자는 방송인 '하하' 입니다."),
        Quiz(type: .imageQuiz,
             question: "두산:LG전 일명 '레깅스 시구'로 일약 스타덤에 오른 인물은 누구일까요?",
             imageUrl: URL(string: "https://dimg.donga.com/wps/SPORTS/IMAGE/2013/08/29/57313806.2.jpg")!,
             options: ["에스파", "제시", "카리나", "클라라"],
             correctAnswer: "클라라",
             explanation: "이미지 속 시구자는 배우 '클라라'로 이 시구로 인해 엄청난 바이럴을 일으키며 스타덤에 올랐습니다."),
        Quiz(type: .imageQuiz,
             question: "사진 속 팬들이 입고 있는 '유광 점퍼'는 어떤 구단의 상징적인 응원 아이템일까요?",
             imageUrl: URL(string: "https://images.khan.co.kr/article/2016/09/21/l_2016092102000777300184231.jpg")!,
             options: ["LG 트윈스", "롯데 자이언츠", "한화 이글스", "KIA 타이거즈"],
             correctAnswer: "LG 트윈스",
             explanation: "서울을 연고로 하는  LG 트윈스 팬들의 응원 아이템입니다."),
        Quiz(type: .imageQuiz,
             question: "아래 이미지속의 선수가 마지막으로 소속했던 KBO리그 팀은?",
             imageUrl: URL(string: "https://www.chosun.com/resizer/v2/SYJ4BA7HJBOZHNUNWNOAQCXV2E.jpg?auth=c1e637c5d2d45105039118da38746def18d8963c3eb7bfe959b2a6ae8b8db4d1&width=616")!,
             options: ["두산 베어스", "LG 트윈스", "SSG 랜더스", "키움 히어로즈"],
             correctAnswer: "키움 히어로즈",
             explanation: "사진 속 선수는 이정후 선수이며, 현재 MLB 리그 샌프란시스코의 유격수로 활약하고 있습니다. 이정후 선수가 마지막으로 속했던 KBO리그 팀은 키움 히어로즈입니다."),
        Quiz(type: .imageQuiz,
             question: "다음은 어떤 구단의 로고일까요?",
             imageUrl: URL(string: "https://t1.daumcdn.net/media/img-section/sports13/logo/team/1/HH_300300.png")!,
             options: ["두산 베어스", "LG 트윈스", "SSG 랜더스", "한화 Eagles"],
             correctAnswer: "한화 Eagles",
             explanation: "대전을 연고로 하는  한화 Eagles 로고입니다."),

        Quiz(type: .imageQuiz,
             question: "이 선수는 누구일까요?",
             imageUrl: URL(string: "https://search.pstatic.net/sunny/?src=https%3A%2F%2Fimg.hani.co.kr%2Fsection-image%2Fpictorial%2Fnew%2F006008002%2Fimg%2F97_2070802u4753.00.jpg&type=sc960_832"),
             options: ["이승엽", "양의지", "김현수", "강민호"],
             correctAnswer: "이승엽",
             explanation: "홈런왕으로 불린  삼성 라이온즈의 전설, 이승엽 선수입니다."),
        Quiz(type: .imageQuiz,
             question: "이 사진은 어떤 구장의 모습인가요?",
             imageUrl: URL(string: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Jamsil_Baseball_Stadium_panorama_%28April_28_2017%29.jpg"),
             options: ["고척돔", "사직구장", "잠실구장", "문학구장"],
             correctAnswer: "잠실구장",
             explanation: "잠실구장은 LG 트윈스와  두산 베어스의 홈구장입니다."),
        Quiz(type: .imageQuiz,
             question: "이 짤은 글러브를  꺼내서 무언가를 하는 모습입니다. 왜일까요?",
             imageUrl: URL(string: "https://tse2.mm.bing.net/th/id/OIP.FWO5M_eGo9v-khLl9s1rFAHaNK?r=0&pid=Api"),
             options: ["응원한다", "병살 유도", "친척에게", "장난치는 중"],
             correctAnswer: "장난치는 중",
             explanation: "투수와 포수가 웃으며 손가락으로 장난하는  귀여운 장면이 담겨 있습니다."),
        Quiz(type: .imageQuiz,
             question: "관중석이 인형으로  가득 찬 이 장면은 왜 유명할까요?",
             imageUrl: URL(string: "https://i.kym-cdn.com/photos/images/newsfeed/001/857/847/125.jpg"),
             options: ["팬이 모였다", "인형 마케팅", "코로나 시대 응원대체", "선수들 장난"],
             correctAnswer: "코로나 시대 응원대체",
             explanation: "관중 없이 열린 경기에서  구단들이 인형을 대신 배치한 웃픈 풍경입니다."),
        Quiz(type: .questionQuiz,
             question: "KBO에서 '벌떼' 불펜이라 하면  무엇을 뜻할까요?",
             imageUrl: nil,
             options: ["여러 투수 교체 작전", "벌처럼 빠른 주자", "야구 응원단", "코치진 작전"],
             correctAnswer: "여러 투수 교체 작전",
             explanation: "짧은 이닝마다 투수를 바꾸는 불펜 운영 전략입니다."),
        Quiz(type: .questionQuiz,
             question: "KBO에서 '벌크업'이란 보통  무엇을 의미할까요?",
             imageUrl: nil,
             options: ["체격 불리기", "타구 속도 증가", "불펜 강화", "순위 상승"],
             correctAnswer: "체격 불리기",
             explanation: "휴식기 또는 시즌 중에 선수 체중과 근력을 늘리는 것입니다."),
        Quiz(type: .questionQuiz,
             question: "양의지 선수는 어느  구단에서 데뷔했을까요?",
             imageUrl: nil,
             options: ["두산 베어스", "NC 다이노스", "KIA 타이거즈", "LG 트윈스"],
             correctAnswer: "두산 베어스",
             explanation: "양의지는 두산 베어스에서 2007년 프로 데뷔했습니다."),
        Quiz(type: .questionQuiz,
             question: " 2025 시즌 기준, 양의지  선수 신장은 얼마일까요? ",
             imageUrl: nil,
             options: ["179cm", "183cm", "185cm", "178cm"],
             correctAnswer: "179cm",
             explanation: " 양의지의 키는  180cm입니다. "),
        Quiz(type: .questionQuiz,
             question: " 이승엽은 한 시즌 최다  홈런(56개)을 언제 달성했을까요? ",
             imageUrl: nil,
             options: ["2003년", "1999년", "2001년", "2002년"],
             correctAnswer: "2003년",
             explanation: " 2003년 이승엽은  56홈런으로 당시 아시아 신기록을 세웠습니다. "),
        Quiz(type: .questionQuiz,
             question: " 2025년 한화 이글스의  채은성 선수의 등번호는 무엇인가요? ",
             imageUrl: nil,
             options: ["17번", "22번", "50번", "10번"],
             correctAnswer: "22번",
             explanation: " 채은성은 2025 시즌 한화에서  등번호 22번을 사용합니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 트윈스의  문보경 선수의 포지션은 무엇인가요? ",
             imageUrl: nil,
             options: ["외야수", "포수", "내야수", "투수"],
             correctAnswer: "내야수",
             explanation: " 문보경은 LG의 주전  3루수로 활약 중입니다. "),
        Quiz(type: .questionQuiz,
             question: " 2025년 기준 한화 이글스의  주장 역할을 맡고 있는 선수는 누구인가요? ",
             imageUrl: nil,
             options: ["노시환", "이도윤", "박상언", "채은성"],
             correctAnswer: "노시환",
             explanation: " 노시환은 2025 시즌  한화의 주장을 맡고 있습니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 트윈스의  오지환 선수의 주 포지션은 무엇인가요? ",
             imageUrl: nil,
             options: ["3루수", "유격수", "2루수", "외야수"],
             correctAnswer: "유격수",
             explanation: " 오지환은 LG의 주전  유격수입니다. "),
        Quiz(type: .questionQuiz,
             question: " 2025년 한화 이글스 소속  좌완 투수 황준서의 등번호는? ",
             imageUrl: nil,
             options: ["25번", "31번", "29번", "19번"],
             correctAnswer: "29번",
             explanation: " 황준서는 2025 시즌  등번호 29번을 사용합니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 트윈스의  2025년 신인 유망주는 누구인가요? ",
             imageUrl: nil,
             options: ["이상영", "김범석", "최성훈", "김도영"],
             correctAnswer: "김범석",
             explanation: " 김범석은 2025년 LG의  기대를 받는 신인 포수입니다. "),
        Quiz(type: .questionQuiz,
             question: " 2025 시즌 한화의 포수 중  베테랑 역할을 하는 선수는 누구인가요? ",
             imageUrl: nil,
             options: ["허인서", "최재훈", "이재원", "윤준호"],
             correctAnswer: "최재훈",
             explanation: " 최재훈은 한화의 주전 포수로서  안정적인 리드를 보여줍니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 투수진에서 2025년 기준  마무리 역할을 맡고 있는 선수는 누구인가요? ",
             imageUrl: nil,
             options: ["김진성", "이정용", "장현식", "최원태"],
             correctAnswer: "이정용",
             explanation: " 이정용은 LG에서  마무리 투수로 활약 중입니다. "),
        Quiz(type: .questionQuiz,
             question: " 한화 이글스의 2025 시즌  외야 유망주는 누구인가요? ",
             imageUrl: nil,
             options: ["정은원", "김태연", "이도윤", "윤준호"],
             correctAnswer: "이도윤",
             explanation: " 이도윤은 빠른 성장세를 보이는  한화의 외야 유망주입니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 트윈스에서 2025년 기준  가장 많은 도루를 기록한 선수는? ",
             imageUrl: nil,
             options: ["박해민", "문보경", "오지환", "김현수"],
             correctAnswer: "박해민",
             explanation: " 박해민은 빠른 발로  도루왕을 여러 차례 차지했습니다. "),
        Quiz(type: .questionQuiz,
             question: " 한화 주장 역할을 맡은 선수는 누구인가요? ",
             imageUrl: nil,
             options: ["노시환", "이도윤", "박상언", "채은성"],
             correctAnswer: "노시환",
             explanation: " 노시환은 2025 시즌  한화 이글스의 주장입니다. "),
        Quiz(type: .questionQuiz,
             question: " 한화 포수 최재훈 선수의  등번호는 무엇인가요? ",
             imageUrl: nil,
             options: ["13번", "20번", "59번", "7번"],
             correctAnswer: "13번",
             explanation: " 최재훈은 한화의 주전 포수로  등번호 13번을 착용합니다. "),
        Quiz(type: .questionQuiz,
             question: " 한화 좌완 투수 황준서의  등번호는? ",
             imageUrl: nil,
             options: ["29번", "26번", "11번", "38번"],
             correctAnswer: "29번",
             explanation: " 황준서는 2025 시즌  등번호 29번을 사용 중입니다. "),
        Quiz(type: .questionQuiz,
             question: " 한화 외야 유망주 이도윤의  주요 포지션은? ",
             imageUrl: nil,
             options: ["중견수", "좌익수", "우익수", "지명타자"],
             correctAnswer: "중견수",
             explanation: " 이도윤은 빠른 주루와  수비력을 가진 중견수입니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 문보경 선수의  등번호는 무엇인가요? ",
             imageUrl: nil,
             options: ["2번", "5번", "31번", "22번"],
             correctAnswer: "2번",
             explanation: " 문보경은 2025년 LG에서  등번호 2번을 착용합니다. "),
        Quiz(type: .questionQuiz,
             question: " LG는 2025년에 어떤 포수를  신인으로 영입했나요? ",
             imageUrl: nil,
             options: ["김범석", "이상영", "신민재", "박동원"],
             correctAnswer: "김범석",
             explanation: " 김범석은 LG의  기대 신인 포수입니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 마무리 투수 이정용의  등번호는? ",
             imageUrl: nil,
             options: ["50번", "18번", "21번", "63번"],
             correctAnswer: "50번",
             explanation: " 이정용은 2025년 LG의  마무리 투수로 활약 중입니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 외야수 김현수의  등번호는 무엇인가요? ",
             imageUrl: nil,
             options: ["18번", "22번", "5번", "9번"],
             correctAnswer: "18번",
             explanation: " 김현수는 LG 외야진의  핵심으로 18번을 달고 있습니다. "),
        Quiz(type: .questionQuiz,
             question: " LG 유격수 오지환의  등번호는? ",
             imageUrl: nil,
             options: ["5번", "2번", "9번", "21번"],
             correctAnswer: "5번",
             explanation: " 오지환은 유격수로  등번호 5번을 착용 중입니다. "),
        Quiz(type: .questionQuiz,
             question: " 두산 베어스의 주전 포수  양의지의 등번호는? ",
             imageUrl: nil,
             options: ["25번", "10번", "20번", "47번"],
             correctAnswer: "25번",
             explanation: " 양의지는 통산  1000경기 이상 출전한 베테랑입니다. "),
        Quiz(type: .questionQuiz,
             question: " 키움 히어로즈 2025년  신인왕 후보 투수는 누구인가요? ",
             imageUrl: nil,
             options: ["이재영", "소형준", "이주형", "문우람"],
             correctAnswer: "이재영",
             explanation: " 이재영은  신인왕 후보로 주목받는 투수입니다. "),
        Quiz(type: .questionQuiz,
             question: " 삼성 라이온즈의 에이스  유희관의 등번호는? ",
             imageUrl: nil,
             options: ["46번", "18번", "55번", "27번"],
             correctAnswer: "46번",
             explanation: " 유희관은 삼성에서  46번을 착용하는 좌완 투수입니다. "),
        Quiz(type: .questionQuiz,
             question: " 롯데 자이언츠의  주전 1루수는 누구인가요? ",
             imageUrl: nil,
             options: ["박세웅", "박민우", "황재균", "안치홍"],
             correctAnswer: "박민우",
             explanation: " 박민우는 2025년  롯데 주전 1루수를 맡고 있습니다. "),
        Quiz(type: .questionQuiz,
             question: " KT Wiz에서 2025년  클로저 역할을 하는 선수는? ",
             imageUrl: nil,
             options: ["김민수", "장시환", "이대은", "소형준"],
             correctAnswer: "장시환",
             explanation: " 장시환은 KT의  마무리 투수로 활약 중입니다. "),
        Quiz(type: .questionQuiz,
             question: " NC 다이노스의  외국인 타자는 누구인가요? ",
             imageUrl: nil,
             options: ["라이언 알칸토", "페게로", "딕슨 마차도", "타이론 우즈"],
             correctAnswer: "라이언 알칸토",
             explanation: " 알칸토는 2025 시즌 NC의  주전 외국인 타자입니다. "),
        Quiz(type: .questionQuiz,
             question: " SSG 랜더스의  중심타자 최정의 등번호는? ",
             imageUrl: nil,
             options: ["14번", "35번", "55번", "2번"],
             correctAnswer: "14번",
             explanation: " 최정은 SSG의 중심타자로  14번을 달고 있습니다. "),
        Quiz(type: .questionQuiz,
             question: " KIA 타이거즈의  간판타자 김선빈의 포지션은? ",
             imageUrl: nil,
             options: ["유격수", "2루수", "3루수", "포수"],
             correctAnswer: "유격수",
             explanation: " 김선빈은 KIA의  주전 유격수입니다. "),
        
        // OX 퀴즈
        Quiz(type: .oxQuiz,
             question: "KBO 리그는  1982년에 출범했다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: "KBO 리그는 1982년  6개 구단으로 시작했습니다."),
        Quiz(type: .oxQuiz,
             question: "롯데 자이언츠의 홈구장은  잠실 야구장이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "롯데 자이언츠의 홈구장은  부산 사직 야구장입니다."),
        Quiz(type: .oxQuiz,
             question: "삼성 라이온즈는  KBO 리그 최다 우승팀이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "KIA 타이거즈가  11회 우승으로 최다 우승팀입니다."),
        Quiz(type: .oxQuiz,
             question: "잠실에 새로 들어설 야구장은 3만3천 석 규모로, 돔구장이 아닌 개방형 구장으로 지어질 예정이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: "3만3천석 규모의 개방형 구장으로 지어질 예정이며 새로운 잠실 야구장은 2029년 완공이 목표인 것으로 알려져 있다."),
        Quiz(type: .oxQuiz,
             question: "삼성 라이온즈는  KBO 리그 최다 우승팀이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "KIA 타이거즈가  11회 우승으로 최다 우승팀입니다."),
        Quiz(type: .oxQuiz,
             question: "삼성 라이온즈는  KBO 리그 최다 우승팀이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "KIA 타이거즈가  11회 우승으로 최다 우승팀입니다."),
        Quiz(type: .oxQuiz,
             question: "야구는 한 팀당  11명이 경기에 출전한다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "야구는 수비 시  9명이 출전합니다."),
        Quiz(type: .oxQuiz,
             question: "한 경기의 기본 이닝 수는  9이닝이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: "KBO 정규 경기의  기본 이닝 수는 9이닝입니다."),
        Quiz(type: .oxQuiz,
             question: "삼진을 4번 당하면  타자는 아웃된다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "삼진은 스트라이크 3개로  아웃입니다."),
        Quiz(type: .oxQuiz,
             question: "홈런은 1점만  득점할 수 있다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "홈런은 주자 수에 따라  최대 4점까지 낼 수 있습니다."),
        Quiz(type: .oxQuiz,
             question: "도루는 수비수가  실책했을 때만 가능하다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "도루는 수비 실책 없이도  주자가 직접 시도할 수 있습니다."),
        Quiz(type: .oxQuiz,
             question: "KBO는 한국야구위원회의  약자이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: "KBO는 ‘Korea Baseball Organization’의  약자입니다."),
        Quiz(type: .oxQuiz,
             question: "투수는 수비수가 아니다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "투수도 공을 던지고  타구를 막는 수비수입니다."),
        Quiz(type: .oxQuiz,
             question: " KBO 리그에서  홈런으로 끝나는 경기를  끝내기 홈런이라 부른다.",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: " 끝내기 홈런은 경기 마지막에  홈팀이 이기며 종료되는 홈런입니다. "),
        Quiz(type: .oxQuiz,
             question: " KBO 리그에서는  투수가 3타자 연속 삼진을  잡으면 바로 교체된다.",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: " 삼진과 교체는  관계가 없습니다. "),
        Quiz(type: .oxQuiz,
             question: " LG 트윈스는  창단 이후 단 한 번도  한국시리즈를 우승한 적이 없다.",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: " LG는 1990년과 1994년,  그리고 2023년에 우승했습니다. "),
        Quiz(type: .oxQuiz,
             question: " KBO에서는  동점으로 12회까지 가면  무승부 처리된다.",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: " 연장 12회까지 동점이면  무승부입니다. "),
        Quiz(type: .oxQuiz,
             question: " 야구 배트는 금속 재질만  사용할 수 있다.",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: " KBO에서는 목재 배트를  사용합니다. "),
        Quiz(type: .oxQuiz,
             question: " 만루홈런은  홈런 1개로 4점을 얻는  가장 높은 점수의 타격이다.",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: " 만루홈런은 타자 본인 포함  4명이 득점하게 됩니다. "),
        Quiz(type: .oxQuiz,
             question: " SSG 김광현은 2025년  KBO 최고 연봉자이다.",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: " 김광현은 2025년에  30억원으로 최고 연봉자입니다. "),
        
        // 질문 퀴즈 (선다형)
        Quiz(type: .questionQuiz,
             question: "다음 중 KBO 리그에 속하지 않는  구단은?",
             imageUrl: nil,
             options: ["키움 히어로즈", "kt wiz", "고양 히어로즈", "한화 이글스"],
             correctAnswer: "고양 히어로즈",
             explanation: "고양 히어로즈는  키움 히어로즈 퓨처스 팀입니다."),
        Quiz(type: .questionQuiz,
             question: "2024년 정규리그 우승팀은  어디일까요?",
             imageUrl: nil,
             options: ["LG 트윈스", "KT 위즈", "SSG 랜더스", "두산 베어스"],
             correctAnswer: "LG 트윈스", // 2024년 우승팀이 LG 트윈스라고 가정
             explanation: "2024년 KBO 정규리그 우승팀은  LG 트윈스입니다."),
        Quiz(type: .questionQuiz,
             question: "다음 중 '최정' 선수의  소속팀은?",
             imageUrl: nil,
             options: ["두산 베어스", "SSG 랜더스", "NC 다이노스", "삼성 라이온즈"],
             correctAnswer: "SSG 랜더스",
             explanation: "KBO 홈런왕 최정 선수는  SSG 랜더스 소속입니다."),
        Quiz(type: .questionQuiz,
             question: "다음 중 '엘리저 에르난데스' 선수의 소속팀은?",
             imageUrl: nil,
             options: ["두산 베어스", "SSG 랜더스", "LG 트윈스"],
             correctAnswer: "LG 트윈스",
             explanation: "2024년 6월까지  LA 다저스 소속이었던  엘리저 에르난데스 선수는 LG 트윈스 소속입니다."),
        Quiz(type: .questionQuiz,
             question: "야구에서 '병살타'는  어떤 상황에서 기록될까요? ",
             imageUrl: nil,
             options: ["수비수의 실책을 한", "타자 헛스윙 삼진", "타구로 두명 아웃", "주자가 베이스 지남"],
             correctAnswer: "타구로 인해 두 명의 주자가 아웃",
             explanation: "미스 플레이 없이  연속으로 아웃 카운트가  두 개 생기는 경우를 뜻한다"),
        Quiz(type: .questionQuiz,
             question: "주자가 1루에 있을떄,  타자가 병살타를 치면 몇 명이 아웃 될까요? ",
             imageUrl: nil,
             options: ["1 명", "2 명", "3 명", "0 명"],
             correctAnswer: "2 명",
             explanation: "미스 플레이 없이  연속으로 아웃 카운트가  두 개 생기는 경우를 뜻한다"),
        Quiz(type: .questionQuiz,
             question: "KBO 역대 최다승 투수는 누구인가요? ",
             imageUrl: nil,
             options: ["선동열", "최동원", "송진우", "정민철"],
             correctAnswer: "송진우",
             explanation: "은퇴 후에도 지도자로 활동 하고 있다"),
        Quiz(type: .questionQuiz,
             question: "‘라이언 킹’이라는 별명을 가진  KBO 레전드 선수는 누구인가요?",
             imageUrl: nil,
             options: ["이승엽", "박찬호", "양준혁", "김현수"],
             correctAnswer: "이승엽",
             explanation: "이승엽은 삼성 라이온즈의 상징으로,  '라이언 킹'이라는 별명으로 불렸습니다."),
        Quiz(type: .questionQuiz,
             question: "KBO 최초 외국인  홈런왕은 누구인가요?",
             imageUrl: nil,
             options: ["타이론 우즈", "펠릭스 호세", "찰리 헤이즈", "로사도"],
             correctAnswer: "타이론 우즈",
             explanation: "타이론 우즈는 1998년 홈런왕을  차지한 최초의 외국인 선수입니다."),
        Quiz(type: .questionQuiz,
             question: "KBO에서 ‘사직대첩’으로  유명한 구장은 어디인가요?",
             imageUrl: nil,
             options: ["잠실", "대구", "광주", "사직"],
             correctAnswer: "사직",
             explanation: "롯데 자이언츠의 홈구장 사직야구장은  열정적인 팬문화로  '사직대첩'이라는 별명이 생겼습니다."),
        Quiz(type: .questionQuiz,
             question: "LG 트윈스의 홈구장은 어디인가요?",
             imageUrl: nil,
             options: ["잠실", "문학", "고척", "대전"],
             correctAnswer: "잠실",
             explanation: "LG 트윈스와 두산 베어스는  잠실야구장을 공동으로  사용하고 있습니다."),
        Quiz(type: .questionQuiz,
             question: "KBO 리그 10번째 팀으로 창단된 구단은 어디인가요?",
             imageUrl: nil,
             options: ["NC 다이노스", "kt 위즈", "SSG 랜더스", "키움 히어로즈"],
             correctAnswer: "kt 위즈",
             explanation: "kt 위즈는 2015년 정식 리그에  합류한 KBO의 10번째 구단입니다."),
        Quiz(type: .questionQuiz,
             question: "야구 경기에서 총 몇 명이 수비에 나가나요?",
             imageUrl: nil,
             options: ["7명", "8명", "9명", "10명"],
             correctAnswer: "9명",
             explanation: "야구 수비는 투수 포함  총 9명이 수비를 담당합니다."),
        Quiz(type: .questionQuiz,
             question: "타자가 공을 3번 헛스윙하면 어떻게 될까요?",
             imageUrl: nil,
             options: ["볼넷", "홈런", "아웃", "2루 진루"],
             correctAnswer: "아웃",
             explanation: "3번 스트라이크를 당하면  삼진 아웃으로 처리됩니다."),
        Quiz(type: .questionQuiz,
             question: "KBO 정규시즌에서 한 경기는 보통 몇 이닝으로 구성되나요?",
             imageUrl: nil,
             options: ["5이닝", "7이닝", "9이닝", "12이닝"],
             correctAnswer: "9이닝",
             explanation: "KBO 정규시즌은 보통 9이닝 경기로 진행되며, 동점일 경우 연장전이 있습니다."),
        Quiz(type: .questionQuiz,
             question: "야구에서 공 4개를 받아서 1루로 나가는 것을 무엇이라고 하나요?",
             imageUrl: nil,
             options: ["볼넷", "사구", "삼진", "도루"],
             correctAnswer: "볼넷",
             explanation: "투수가 스트라이크 존에 던지지 못해  볼이 4개가 되면 타자는 1루로 나갈 수 있습니다."),
        Quiz(type: .questionQuiz,
             question: "타자가 공을 치지 않고  1루로 나가는 방법은 무엇인가요?",
             imageUrl: nil,
             options: ["도루", "볼넷", "사구", "홈런"],
             correctAnswer: "볼넷",
             explanation: "볼이 4개가 되면  타자는 자동으로 1루로 진루할 수 있습니다."),
        Quiz(type: .questionQuiz,
             question: "도루는 어떤 상황에서  성공으로 인정되나요?",
             imageUrl: nil,
             options: ["공이 빠졌을 때", "투수가 던질 때", "포수가 놓쳤을 때", "타자가 칠 때"],
             correctAnswer: "투수가 던질 때",
             explanation: "투수가 던질 때  타자가 치지 않아도 주자가 다음 루로 뛰어가면 도루입니다."),
        Quiz(type: .questionQuiz,
             question: "타자의 타격 성적을 나타내는  대표 지표는 무엇인가요?",
             imageUrl: nil,
             options: ["방어율", "타율", "출루율", "홈런 수"],
             correctAnswer: "타율",
             explanation: "타율은 안타를 친 비율로  타자의 정확도를 보여주는 대표 지표입니다."),
        
        
    ]
    
    func generateRandomQuiz() -> Quiz? {
        guard let randomQuizType = QuizType.allCases.randomElement() else {
            return nil
        }
        
        let quizzesOfType = allQuizzes.filter { $0.type == randomQuizType }
        
        return quizzesOfType.randomElement()
    }
}

