//
//  QuizGenerator.swift
//  BaseaballQuiz
//
//  Created by applys on 7/8/25.
//

import Foundation
import SwiftData


// 퀴즈 유형 열거형
enum QuizType: CaseIterable {
    case imageQuiz // 이미지 퀴즈
    case oxQuiz    // OX 퀴즈
    case questionQuiz // 질문 퀴즈 (4지선다형)
}

// 퀴즈 데이터를 담을 구조체
struct Quiz: Identifiable {
    let id = UUID() // 각 퀴즈를 고유하게 식별하기 위한 ID
    let type: QuizType // 퀴즈 유형
    let question: String // 퀴즈 질문
    let imageUrl: URL? // 이미지 퀴즈일 경우 이미지 URL (옵션)
    let options: [String]? // 4지선다형 퀴즈일 경우 선택지 (옵션)
    let correctAnswer: String // 정답
    let explanation: String? // 정답에 대한 추가 설명 (옵션)
}


class QuizGenerator {
    private let allQuizzes: [Quiz] = [
        // 이미지 퀴즈
        Quiz(type: .imageQuiz,
             question: "이 선수는 누구일까요?",
             imageUrl: URL(string: "https://dimg.donga.com/wps/NEWS/IMAGE/2024/09/06/126884040.2.jpg")!,
             options: ["김광현", "류현진", "양의지", "이정후"],
             correctAnswer: "류현진",
             explanation: "한국 야구의 괴물 투수, \n 류현진 선수입니다."),
        Quiz(type: .imageQuiz,
             question: "다음은 어떤 구단의 로고일까요?",
             imageUrl: URL(string: "https://upload.wikimedia.org/wikipedia/ko/8/8a/LG_%ED%8A%B8%EC%9C%88%EC%8A%A4_%EB%A1%9C%EA%B3%A0.png")!,
             options: ["두산 베어스", "LG 트윈스", "SSG 랜더스", "NC 다이노스"],
             correctAnswer: "LG 트윈스",
             explanation: "서울을 연고로 하는 \n LG 트윈스 로고입니다."),
        Quiz(type: .imageQuiz,
             question: "이 야구장은 서울의 어느 구단이 함께 홈으로 사용하는 곳일까요?",
             imageUrl: URL(string: "https://img.sbs.co.kr/newimg/news/20230918/201834693.jpg")!,
             options: ["두산 & 키움", "LG & 키움", "두산 & LG", "SSG & KT"],
             correctAnswer: "두산 & LG",
             explanation: "서울을 연고로 하는 두 팀인 \n 두산베어스와 LG트윈스입니다."),
        Quiz(type: .imageQuiz,
             question: "아래 이미지에서 시구를 하는 사람은 누구일까요?",
             imageUrl: URL(string: "https://spnimage.edaily.co.kr/images/photo/files/NP/S/2016/04/PS16041000071.jpg")!,
             options: ["김범수", "하하", "노홍철", "유재석"],
             correctAnswer: "하하",
             explanation: "이미지 속 시구자는 방송인 '하하' 입니다."),
        Quiz(type: .imageQuiz,
             question: "두산:LG전 일명 '레깅스 시구'로 일약 스타덤에 오른 인물은 누구일까요?",
             imageUrl: URL(string: "https://dimg.donga.com/wps/SPORTS/IMAGE/2013/08/29/57313806.2.jpg")!,
             options: ["에스파", "제시", "카리나", "클라라"],
             correctAnswer: "클라라",
             explanation: "이미지 속 시구자는 배우 '클라라'로 이 시구로 인해 엄청난 바이럴을 일으키며 스타덤에 올랐습니다."),
        Quiz(type: .imageQuiz,
             question: "사진 속 팬들이 입고 있는 '유광 점퍼'는 어떤 구단의 상징적인 응원 아이템일까요?",
             imageUrl: URL(string: "https://images.khan.co.kr/article/2016/09/21/l_2016092102000777300184231.jpg")!,
             options: ["LG 트윈스", "롯데 자이언츠", "한화 이글스", "KIA 타이거즈"],
             correctAnswer: "LG 트윈스",
             explanation: "서울을 연고로 하는 \n LG 트윈스 팬들의 응원 아이템입니다."),
        Quiz(type: .imageQuiz,
             question: "아래 이미지속의 선수가 마지막으로 소속했던 KBO리그 팀은?",
             imageUrl: URL(string: "https://www.chosun.com/resizer/v2/SYJ4BA7HJBOZHNUNWNOAQCXV2E.jpg?auth=c1e637c5d2d45105039118da38746def18d8963c3eb7bfe959b2a6ae8b8db4d1&width=616")!,
             options: ["두산 베어스", "LG 트윈스", "SSG 랜더스", "키움 히어로즈"],
             correctAnswer: "키움 히어로즈",
             explanation: "사진 속 선수는 이정후 선수이며, 현재 MLB 리그 샌프란시스코의 유격수로 활약하고 있습니다. 이정후 선수가 마지막으로 속했던 KBO리그 팀은 키움 히어로즈입니다."),
        Quiz(type: .imageQuiz,
             question: "다음은 어떤 구단의 로고일까요?",
             imageUrl: URL(string: "https://t1.daumcdn.net/media/img-section/sports13/logo/team/1/HH_300300.png")!,
             options: ["두산 베어스", "LG 트윈스", "SSG 랜더스", "한화 Eagles"],
             correctAnswer: "한화 Eagles",
             explanation: "대전을 연고로 하는 \n 한화 Eagles 로고입니다."),
        Quiz(type: .imageQuiz,
             question: "이 유니폼은 어느 KBO 팀의 것일까요?",
             imageUrl: URL(string: "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyNDAxMzBfMjMw%2FMDAxNzA2NjA4MDkzMzQw.xnpy_FI_QtYVG5OPUB8fmHrnBa5tiDdvwZDulFQWGKkg.HN1NpT89ZyzMjQ00MUK2elybO4b1i9JWJfQEeoHZFEMg.JPEG.like3457%2F20240130%25A3%25DF184716.jpg&type=sc960_832"),
             options: ["두산 베어스", "LG 트윈스", "한화 이글스", "삼성 라이온즈"],
             correctAnswer: "두산 베어스",
             explanation: "검정색과 회색이 섞인 이 유니폼은 \n 두산 베어스를 상징합니다."),
        Quiz(type: .imageQuiz,
             question: "이 선수는 누구일까요?",
             imageUrl: URL(string: "https://search.pstatic.net/sunny/?src=https%3A%2F%2Fimg.hani.co.kr%2Fsection-image%2Fpictorial%2Fnew%2F006008002%2Fimg%2F97_2070802u4753.00.jpg&type=sc960_832"),
             options: ["이승엽", "양의지", "김현수", "강민호"],
             correctAnswer: "이승엽",
             explanation: "홈런왕으로 불린 \n 삼성 라이온즈의 전설, 이승엽 선수입니다."),
        Quiz(type: .imageQuiz,
             question: "이 사진은 어떤 구장의 모습인가요?",
             imageUrl: URL(string: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Jamsil_Baseball_Stadium_panorama_%28April_28_2017%29.jpg"),
             options: ["고척돔", "사직구장", "잠실구장", "문학구장"],
             correctAnswer: "잠실구장",
             explanation: "잠실구장은 LG 트윈스와 \n 두산 베어스의 홈구장입니다."),
        Quiz(type: .imageQuiz,
             question: "이 짤은 글러브를 \n 꺼내서 무언가를 하는 모습입니다. 왜일까요?",
             imageUrl: URL(string: "https://tse2.mm.bing.net/th/id/OIP.FWO5M_eGo9v-khLl9s1rFAHaNK?r=0&pid=Api"),
             options: ["응원한다", "병살 유도", "친척에게", "장난치는 중"],
             correctAnswer: "장난치는 중",
             explanation: "투수와 포수가 웃으며 손가락으로 장난하는 \n 귀여운 장면이 담겨 있습니다."),
        Quiz(type: .imageQuiz,
             question: "관중석이 인형으로 \n 가득 찬 이 장면은 왜 유명할까요?",
             imageUrl: URL(string: "https://i.kym-cdn.com/photos/images/newsfeed/001/857/847/125.jpg"),
             options: ["팬이 모였다", "인형 마케팅", "코로나 시대 응원대체", "선수들 장난"],
             correctAnswer: "코로나 시대 응원대체",
             explanation: "관중 없이 열린 경기에서 \n 구단들이 인형을 대신 배치한 웃픈 풍경입니다."),
        
        
        // OX 퀴즈
        Quiz(type: .oxQuiz,
             question: "KBO 리그는 \n 1982년에 출범했다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: "KBO 리그는 1982년 \n 6개 구단으로 시작했습니다."),
        Quiz(type: .oxQuiz,
             question: "롯데 자이언츠의 홈구장은 \n 잠실 야구장이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "롯데 자이언츠의 홈구장은 \n 부산 사직 야구장입니다."),
        Quiz(type: .oxQuiz,
             question: "삼성 라이온즈는 \n KBO 리그 최다 우승팀이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "KIA 타이거즈가 \n 11회 우승으로 최다 우승팀입니다."),
        Quiz(type: .oxQuiz,
             question: "잠실에 새로 들어설 야구장은 \n3만3천 석 규모로, \n돔구장이 아닌 개방형 구장으로 \n지어질 예정이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: "3만3천석 규모의 개방형 구장으로 지어질 \n예정이며 새로운 잠실 야구장은 \n2029년 완공이 목표인 것으로 \n알려져 있다."),
        Quiz(type: .oxQuiz,
             question: "삼성 라이온즈는 \n KBO 리그 최다 우승팀이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "KIA 타이거즈가 \n 11회 우승으로 최다 우승팀입니다."),
        Quiz(type: .oxQuiz,
             question: "삼성 라이온즈는 \n KBO 리그 최다 우승팀이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "KIA 타이거즈가 \n 11회 우승으로 최다 우승팀입니다."),
        Quiz(type: .oxQuiz,
             question: "야구는 한 팀당 \n 11명이 경기에 출전한다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "야구는 수비 시 \n 9명이 출전합니다."),
        Quiz(type: .oxQuiz,
             question: "한 경기의 기본 이닝 수는 \n 9이닝이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: "KBO 정규 경기의 \n 기본 이닝 수는 9이닝입니다."),
        Quiz(type: .oxQuiz,
             question: "삼진을 4번 당하면 \n 타자는 아웃된다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "삼진은 스트라이크 3개로 \n 아웃입니다."),
        Quiz(type: .oxQuiz,
             question: "홈런은 1점만 \n 득점할 수 있다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "홈런은 주자 수에 따라 \n 최대 4점까지 낼 수 있습니다."),
        Quiz(type: .oxQuiz,
             question: "도루는 수비수가 \n 실책했을 때만 가능하다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "도루는 수비 실책 없이도 \n 주자가 직접 시도할 수 있습니다."),
        Quiz(type: .oxQuiz,
             question: "KBO는 한국야구위원회의 \n 약자이다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "O",
             explanation: "KBO는 ‘Korea Baseball Organization’의 \n 약자입니다."),
        Quiz(type: .oxQuiz,
             question: "투수는 수비수가 아니다. (O/X)",
             imageUrl: nil,
             options: nil,
             correctAnswer: "X",
             explanation: "투수도 공을 던지고 \n 타구를 막는 수비수입니다."),
        
        // 질문 퀴즈 (선다형)
        Quiz(type: .questionQuiz,
             question: "다음 중 KBO 리그에 속하지 않는 \n 구단은?",
             imageUrl: nil,
             options: ["키움 히어로즈", "kt wiz", "고양 히어로즈", "한화 이글스"],
             correctAnswer: "고양 히어로즈",
             explanation: "고양 히어로즈는 \n 키움 히어로즈 퓨처스 팀입니다."),
        Quiz(type: .questionQuiz,
             question: "2024년 정규리그 우승팀은 \n 어디일까요?",
             imageUrl: nil,
             options: ["LG 트윈스", "KT 위즈", "SSG 랜더스", "두산 베어스"],
             correctAnswer: "LG 트윈스", // 2024년 우승팀이 LG 트윈스라고 가정
             explanation: "2024년 KBO 정규리그 우승팀은 \n LG 트윈스입니다."),
        Quiz(type: .questionQuiz,
             question: "다음 중 '최정' 선수의 \n 소속팀은?",
             imageUrl: nil,
             options: ["두산 베어스", "SSG 랜더스", "NC 다이노스", "삼성 라이온즈"],
             correctAnswer: "SSG 랜더스",
             explanation: "KBO 홈런왕 최정 선수는 \n SSG 랜더스 소속입니다."),
        Quiz(type: .questionQuiz,
             question: "다음 중 '엘리저 에르난데스'\n 선수의 소속팀은?",
             imageUrl: nil,
             options: ["두산 베어스", "SSG 랜더스", "LG 트윈스"],
             correctAnswer: "LG 트윈스",
             explanation: "2024년 6월까지 \n LA 다저스 소속이었던 \n 엘리저 에르난데스 선수는 LG 트윈스 소속입니다."),
        Quiz(type: .questionQuiz,
             question: "야구에서 '병살타'는 \n 어떤 상황에서 기록될까요? ",
             imageUrl: nil,
             options: ["수비수가 실책을 한 경우", "타자가 헛스윙 삼진", "타구로 인해 두 명의 주자가 아웃", "주자가 베이스를 지나친 경우"],
             correctAnswer: "타구로 인해 두 명의 주자가 아웃",
             explanation: "미스 플레이 없이 \n 연속으로 아웃 카운트가 \n 두 개 생기는 경우를 뜻한다"),
        Quiz(type: .questionQuiz,
             question: "주자가 1루에 있을떄, \n 타자가 병살타를 치면 몇 명이 아웃 될까요? ",
             imageUrl: nil,
             options: ["1 명", "2 명", "3 명", "0 명"],
             correctAnswer: "2 명",
             explanation: "미스 플레이 없이 \n 연속으로 아웃 카운트가 \n 두 개 생기는 경우를 뜻한다"),
        Quiz(type: .questionQuiz,
             question: "KBO 역대 최다승 투수는 누구인가요? ",
             imageUrl: nil,
             options: ["선동열", "최동원", "송진우", "정민철"],
             correctAnswer: "송진우",
             explanation: "은퇴 후에도 지도자로 활동 하고 있다"),
        Quiz(type: .questionQuiz,
             question: "‘라이언 킹’이라는 별명을 가진 \n KBO 레전드 선수는 누구인가요?",
             imageUrl: nil,
             options: ["이승엽", "박찬호", "양준혁", "김현수"],
             correctAnswer: "이승엽",
             explanation: "이승엽은 삼성 라이온즈의 상징으로, \n '라이언 킹'이라는 별명으로 불렸습니다."),
        Quiz(type: .questionQuiz,
             question: "KBO 최초 외국인 \n 홈런왕은 누구인가요?",
             imageUrl: nil,
             options: ["타이론 우즈", "펠릭스 호세", "찰리 헤이즈", "로사도"],
             correctAnswer: "타이론 우즈",
             explanation: "타이론 우즈는 1998년 홈런왕을 \n 차지한 최초의 외국인 선수입니다."),
        Quiz(type: .questionQuiz,
             question: "KBO에서 ‘사직대첩’으로 \n 유명한 구장은 어디인가요?",
             imageUrl: nil,
             options: ["잠실", "대구", "광주", "사직"],
             correctAnswer: "사직",
             explanation: "롯데 자이언츠의 홈구장 사직야구장은 \n 열정적인 팬문화로 \n '사직대첩'이라는 별명이 생겼습니다."),
        Quiz(type: .questionQuiz,
             question: "LG 트윈스의 홈구장은 어디인가요?",
             imageUrl: nil,
             options: ["잠실", "문학", "고척", "대전"],
             correctAnswer: "잠실",
             explanation: "LG 트윈스와 두산 베어스는 \n 잠실야구장을 공동으로 \n 사용하고 있습니다."),
        Quiz(type: .questionQuiz,
             question: "KBO 리그 10번째 팀으로 창단된 구단은 어디인가요?",
             imageUrl: nil,
             options: ["NC 다이노스", "kt 위즈", "SSG 랜더스", "키움 히어로즈"],
             correctAnswer: "kt 위즈",
             explanation: "kt 위즈는 2015년 정식 리그에 \n 합류한 KBO의 10번째 구단입니다."),
        Quiz(type: .questionQuiz,
             question: "야구 경기에서 총 몇 명이 수비에 나가나요?",
             imageUrl: nil,
             options: ["7명", "8명", "9명", "10명"],
             correctAnswer: "9명",
             explanation: "야구 수비는 투수 포함 \n 총 9명이 수비를 담당합니다."),
        Quiz(type: .questionQuiz,
             question: "타자가 공을 3번 헛스윙하면 어떻게 될까요?",
             imageUrl: nil,
             options: ["볼넷", "홈런", "아웃", "2루 진루"],
             correctAnswer: "아웃",
             explanation: "3번 스트라이크를 당하면 \n 삼진 아웃으로 처리됩니다."),
        Quiz(type: .questionQuiz,
             question: "KBO 정규시즌에서 한 경기는 보통 몇 이닝으로 구성되나요?",
             imageUrl: nil,
             options: ["5이닝", "7이닝", "9이닝", "12이닝"],
             correctAnswer: "9이닝",
             explanation: "KBO 정규시즌은 보통 9이닝 경기로 진행되며, \n 동점일 경우 연장전이 있습니다."),
        Quiz(type: .questionQuiz,
             question: "야구에서 공 4개를 받아서 1루로 나가는 것을 무엇이라고 하나요?",
             imageUrl: nil,
             options: ["볼넷", "사구", "삼진", "도루"],
             correctAnswer: "볼넷",
             explanation: "투수가 스트라이크 존에 던지지 못해 \n 볼이 4개가 되면 타자는 1루로 나갈 수 있습니다."),
        Quiz(type: .questionQuiz,
             question: "타자가 공을 치지 않고 \n 1루로 나가는 방법은 무엇인가요?",
             imageUrl: nil,
             options: ["도루", "볼넷", "사구", "홈런"],
             correctAnswer: "볼넷",
             explanation: "볼이 4개가 되면 \n 타자는 자동으로 1루로 진루할 수 있습니다."),
        Quiz(type: .questionQuiz,
             question: "도루는 어떤 상황에서 \n 성공으로 인정되나요?",
             imageUrl: nil,
             options: ["공이 빠졌을 때", "투수가 던질 때", "포수가 놓쳤을 때", "타자가 칠 때"],
             correctAnswer: "투수가 던질 때",
             explanation: "투수가 던질 때 \n 타자가 치지 않아도 주자가 다음 루로 뛰어가면 도루입니다."),
        Quiz(type: .questionQuiz,
             question: "타자의 타격 성적을 나타내는 \n 대표 지표는 무엇인가요?",
             imageUrl: nil,
             options: ["방어율", "타율", "출루율", "홈런 수"],
             correctAnswer: "타율",
             explanation: "타율은 안타를 친 비율로 \n 타자의 정확도를 보여주는 대표 지표입니다."),
        
        
    ]
    
    func generateRandomQuiz() -> Quiz? {
        guard let randomQuizType = QuizType.allCases.randomElement() else {
            return nil
        }
        
        let quizzesOfType = allQuizzes.filter { $0.type == randomQuizType }
        
        return quizzesOfType.randomElement()
    }
}

